import { Head, Link } from '@inertiajs/react';
import AppShell from '../../components/AppShell';

export default function Certificate({ certificate }: { certificate: { title: string; description: string | null; number: string; issued_on: string; member: string; issuer: string; member_id: number } }) {
    return <AppShell title="Certificate"><Head title={`${certificate.member} — ${certificate.title}`} />
        <div className="mx-auto max-w-4xl"><div className="mb-3 flex justify-between print:hidden"><Link href={`/members/${certificate.member_id}/portfolio`} className="font-bold text-brand">← My Areterra</Link><button onClick={() => window.print()} className="rounded-xl bg-brand px-4 py-2 font-bold text-white">Print certificate</button></div>
        <main className="relative overflow-hidden border-[12px] border-double border-amber-400 bg-white px-6 py-16 text-center shadow-xl sm:px-16 sm:py-24"><div className="absolute inset-3 border border-sky-900/20"/><div className="relative"><div className="mx-auto mb-5 grid h-20 w-20 place-items-center rounded-full bg-amber-400 text-4xl">🏆</div><p className="font-bold uppercase tracking-[.35em] text-brand">Areterra Hub</p><h1 className="mt-5 text-4xl font-black text-brand-dark sm:text-6xl">Certificate of Achievement</h1><p className="mt-8 text-lg text-slate-500">This certificate is proudly presented to</p><h2 className="mt-2 text-4xl font-black text-emerald-700 sm:text-5xl">{certificate.member}</h2><p className="mt-8 text-xl text-slate-500">for</p><h3 className="mt-2 text-3xl font-bold text-brand-dark">{certificate.title}</h3>{certificate.description && <p className="mx-auto mt-4 max-w-xl text-lg text-slate-600">{certificate.description}</p>}<div className="mt-14 flex justify-around gap-4 border-t pt-6 text-sm"><span><b>{new Date(certificate.issued_on).toLocaleDateString('en-GB')}</b><br/>Date awarded</span><span><b>{certificate.issuer}</b><br/>Issued by Areterra</span></div><p className="mt-8 text-xs text-slate-400">Certificate {certificate.number}</p></div></main></div>
    </AppShell>;
}
