import { FormEvent, useState } from 'react';
import { Head, Link, router, useForm } from '@inertiajs/react';
import AppShell from '../../components/AppShell';
import Card from '../../components/Card';
import Modal from '../../components/Modal';

interface Example { theme: string; date: string; example: string; source: string }
interface Evidence { from: string; to: string; participation_count: number; activity_titles: string[]; headline: string; themes: { theme: string; count: number; examples: Example[] }[]; photos: { date: string; title: string; description: string | null; media_url: string }[] }
interface Item { id: number; type: string; title: string; description: string | null; date: string | null; certificate_id: number | null }
interface Certificate { id: number; title: string; description: string | null; issued_on: string; number: string; issuer: string }
interface Props { member: { id: number; name: string; photo_url: string | null; interests: string | null }; months: number; evidence: Evidence; items: Item[]; certificates: Certificate[]; achievedGoals: { title: string; description: string | null; date: string | null }[]; canEdit: boolean }

const LABELS: Record<string, string> = { 'practical-skills': 'Practical skills', independence: 'Independence', communication: 'Communication', social: 'Social participation', choice: 'Choice', confidence: 'Confidence', wellbeing: 'Wellbeing' };

export default function Portfolio({ member, months, evidence, items, certificates, achievedGoals, canEdit }: Props) {
    const [adding, setAdding] = useState(false); const [certifying, setCertifying] = useState(false);
    const item = useForm({ type: 'achievement', title: '', description: '', achieved_on: new Date().toISOString().slice(0, 10), visible_to_member: true });
    const cert = useForm({ title: '', description: '', issued_on: new Date().toISOString().slice(0, 10) });
    const submitItem = (e: FormEvent) => { e.preventDefault(); item.post(`/members/${member.id}/portfolio-items`, { onSuccess: () => { setAdding(false); item.reset(); } }); };
    const submitCert = (e: FormEvent) => { e.preventDefault(); cert.post(`/members/${member.id}/certificates`); };
    return <AppShell title={`${member.name} · My Areterra`}>
        <Head title={`${member.name} — My Areterra`} />
        <div className="space-y-4">
            <div className="overflow-hidden rounded-3xl bg-gradient-to-br from-sky-900 via-brand-dark to-emerald-800 p-5 text-white shadow-lg sm:p-8">
                <div className="flex items-center gap-4">{member.photo_url ? <img src={member.photo_url} className="h-20 w-20 rounded-full border-4 border-white/30 object-cover" alt="" /> : <div className="grid h-20 w-20 place-items-center rounded-full bg-white/20 text-3xl font-black">{member.name[0]}</div>}
                    <div><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">My Areterra</p><h1 className="text-3xl font-black sm:text-4xl">{member.name}</h1><p className="mt-1 text-sm text-white/75">Achievements, experiences and brighter futures.</p></div></div>
                {member.interests && <p className="mt-5 rounded-2xl bg-white/10 p-4 text-sm"><b>Things I enjoy:</b> {member.interests}</p>}
            </div>
            <div className="flex flex-wrap items-center gap-2"><Link href={`/members/${member.id}`} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold text-brand">← Profile</Link>{[3,6,12].map(n => <button key={n} onClick={() => router.get(`/members/${member.id}/portfolio`, { months: n })} className={`rounded-xl px-4 py-2 text-sm font-bold ${months === n ? 'bg-brand text-white' : 'border bg-white text-slate-600'}`}>{n} months</button>)}<span className="flex-1" />{canEdit && <><button onClick={() => setAdding(true)} className="rounded-xl bg-sky-100 px-4 py-2 text-sm font-bold text-brand">+ Portfolio item</button><button onClick={() => setCertifying(true)} className="rounded-xl bg-amber-400 px-4 py-2 text-sm font-bold text-amber-950">🏆 Certificate</button></>}</div>
            <Card title="My recent story"><p className="text-lg font-semibold leading-relaxed text-brand-dark">{evidence.headline}</p>{evidence.activity_titles.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{evidence.activity_titles.map(x => <span key={x} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">{x}</span>)}</div>}</Card>
            {evidence.photos.length > 0 && <Card title="Moments to remember"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{evidence.photos.slice(0,9).map((photo,i) => <figure key={`${photo.media_url}-${i}`} className="overflow-hidden rounded-2xl bg-slate-100"><img src={photo.media_url} alt="" className="aspect-square w-full object-cover" /><figcaption className="p-2 text-xs"><b>{photo.title}</b><br/><span className="text-slate-500">{new Date(photo.date).toLocaleDateString('en-GB')}</span></figcaption></figure>)}</div></Card>}
            <div className="grid gap-4 lg:grid-cols-2"><Card title="Outcome evidence"><div className="space-y-3">{evidence.themes.length === 0 && <p className="text-sm text-slate-500">Evidence will appear automatically as staff record activities and daily notes.</p>}{evidence.themes.map(t => <details key={t.theme} className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer font-bold text-brand-dark">{LABELS[t.theme] || t.theme} <span className="ml-1 text-xs text-slate-400">{t.count} examples</span></summary><div className="mt-2 space-y-2">{t.examples.map((e,i) => <div key={i} className="rounded-lg bg-slate-50 p-3 text-sm"><p>{e.example}</p><small className="text-slate-400">{new Date(e.date).toLocaleDateString('en-GB')} · {e.source}</small></div>)}</div></details>)}</div></Card>
                <Card title="Achievements & projects"><div className="space-y-3">{[...items, ...achievedGoals.map((g,i) => ({...g,id:-i-1,type:'goal',certificate_id:null}))].length === 0 && <p className="text-sm text-slate-500">Achievements added here become part of this lasting portfolio.</p>}{[...items, ...achievedGoals.map((g,i) => ({...g,id:-i-1,type:'goal',certificate_id:null}))].map(x => <div key={`${x.type}-${x.id}`} className="rounded-xl bg-gradient-to-r from-amber-50 to-white p-3"><div className="flex justify-between"><b className="text-brand-dark">{x.type === 'certificate' ? '🏆 ' : x.type === 'goal' ? '🎯 ' : '✨ '}{x.title}</b>{x.date && <small className="text-slate-400">{new Date(x.date).toLocaleDateString('en-GB')}</small>}</div>{x.description && <p className="mt-1 text-sm text-slate-600">{x.description}</p>}{x.certificate_id && <Link href={`/certificates/${x.certificate_id}`} className="mt-2 inline-block text-xs font-bold text-brand">View certificate →</Link>}</div>)}</div></Card></div>
            {certificates.length > 0 && <Card title="My certificates"><div className="grid gap-3 sm:grid-cols-2">{certificates.map(c => <Link href={`/certificates/${c.id}`} key={c.id} className="rounded-2xl border-2 border-amber-200 bg-amber-50 p-4"><b className="text-brand-dark">🏆 {c.title}</b><p className="mt-1 text-xs text-slate-500">Issued {new Date(c.issued_on).toLocaleDateString('en-GB')} · {c.number}</p></Link>)}</div></Card>}
        </div>
        <Modal open={adding} title="Add to portfolio" onClose={() => setAdding(false)}><form onSubmit={submitItem} className="space-y-3"><select value={item.data.type} onChange={e=>item.setData('type',e.target.value)} className="w-full rounded-xl border-slate-300"><option value="achievement">Achievement</option><option value="project">Project</option><option value="choice">Choice / preference</option></select><input required placeholder="Title" value={item.data.title} onChange={e=>item.setData('title',e.target.value)} className="w-full rounded-xl border-slate-300"/><textarea placeholder="What happened?" value={item.data.description} onChange={e=>item.setData('description',e.target.value)} className="w-full rounded-xl border-slate-300"/><input type="date" value={item.data.achieved_on} onChange={e=>item.setData('achieved_on',e.target.value)} className="w-full rounded-xl border-slate-300"/><button disabled={item.processing} className="w-full rounded-xl bg-brand p-3 font-bold text-white">Save to portfolio</button></form></Modal>
        <Modal open={certifying} title="Create digital certificate" onClose={() => setCertifying(false)}><form onSubmit={submitCert} className="space-y-3"><input required placeholder="Certificate title" value={cert.data.title} onChange={e=>cert.setData('title',e.target.value)} className="w-full rounded-xl border-slate-300"/><textarea placeholder="What has been completed or achieved?" value={cert.data.description} onChange={e=>cert.setData('description',e.target.value)} className="w-full rounded-xl border-slate-300"/><input required type="date" value={cert.data.issued_on} onChange={e=>cert.setData('issued_on',e.target.value)} className="w-full rounded-xl border-slate-300"/><button disabled={cert.processing} className="w-full rounded-xl bg-amber-400 p-3 font-bold text-amber-950">Create certificate</button></form></Modal>
    </AppShell>;
}
